name: Build Binaries

on:
  push:
    branches:
      - main
  workflow_dispatch:  # allows manual triggering

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          DATE_TAG=$(date +'%Y-%m-%d-%H%M')
          pyinstaller --onefile --windowed src/main.py --name SilverFlag-${{ matrix.os }}-$DATE_TAG

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SilverFlag-${{ matrix.os }}
          path: dist/
