name: Build Binaries

on:
  push:
    branches:
      - main
  workflow_dispatch:  # allows manual triggering

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --windowed src/main.py --name SilverFlag-${{ matrix.os }}
          
      - name: Set build timestamp (Linux/macOS)
        if: runner.os != 'Windows'
        run: echo "DATE_TAG=$(date +'%Y-%m-%d-%H%M')" >> $GITHUB_ENV
      
      - name: Set build timestamp (Windows)
        if: runner.os == 'Windows'
        run: | 
          $dt = Get-Date -Format "yyyy-MM-dd-HHmm"
          echo "DATE_TAG=$dt" >> $env:GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SilverFlag-${{ matrix.os }}
          path: dist/
